package ddlc.yuri.utils.render.imgui.style;

import ddlc.yuri.api.gui.click.novoline.GuiTheme;
import imgui.flag.ImGuiCol;

import java.awt.*;

public final class ImGuiStyles {

    private ImGuiStyles() {
    }

    public static ImGuiStyleSheet novoline() {
        return new ImGuiStyleSheet()
                .rounding(4f, 2f, 2f)
                .windowPadding(10f, 10f)
                .framePadding(6f, 4f)
                .itemSpacing(8f, 6f)
                .color(ImGuiCol.WindowBg, GuiTheme.PANEL, 245)
                .color(ImGuiCol.TitleBgActive, GuiTheme.MODULE_BG, 255)
                .color(ImGuiCol.TitleBg, GuiTheme.MODULE_BG, 255)
                .color(ImGuiCol.FrameBg, GuiTheme.MODULE_BG, 255)
                .color(ImGuiCol.FrameBgHovered, GuiTheme.MODULE_HOVER, 255)
                .color(ImGuiCol.FrameBgActive, GuiTheme.MODULE_HOVER, 255)
                .color(ImGuiCol.CheckMark, GuiTheme.ACCENT, 255)
                .color(ImGuiCol.SliderGrab, GuiTheme.ACCENT, 255)
                .color(ImGuiCol.SliderGrabActive, GuiTheme.ACCENT, 255)
                .color(ImGuiCol.Header, GuiTheme.ACCENT, 120)
                .color(ImGuiCol.HeaderHovered, GuiTheme.ACCENT, 160)
                .color(ImGuiCol.HeaderActive, GuiTheme.ACCENT, 200)
                .color(ImGuiCol.Tab, GuiTheme.MODULE_BG, 255)
                .color(ImGuiCol.TabHovered, GuiTheme.ACCENT, 160)
                .color(ImGuiCol.TabActive, GuiTheme.ACCENT, 220)
                .color(ImGuiCol.Text, GuiTheme.TEXT, 255)
                .color(ImGuiCol.Button, GuiTheme.BUTTON, 180)
                .color(ImGuiCol.ButtonHovered, GuiTheme.ACCENT, 160)
                .color(ImGuiCol.ButtonActive, GuiTheme.ACCENT, 220)
                .color(ImGuiCol.Border, GuiTheme.BUTTON_OUTLINE, 180);
    }

    public static ImGuiStyleSheet regular() {
        Color mainColor = new Color(142, 197, 252);
        Color darker1 = mainColor.darker();
        Color darker2 = mainColor.darker().darker();
        Color darker3 = mainColor.darker().darker().darker();
        Color darker5 = mainColor.darker().darker().darker().darker().darker();

        return new ImGuiStyleSheet()
                .color(ImGuiCol.Text, new Color(219, 237, 226), 224)
                .color(ImGuiCol.TextDisabled, new Color(219, 237, 226), 71)
                .color(ImGuiCol.WindowBg, new Color(22, 22, 22), 255)
                .color(ImGuiCol.ChildBg, new Color(0, 0, 0), 0)
                .color(ImGuiCol.PopupBg, new Color(69, 69, 70), 229)
                .color(ImGuiCol.Border, new Color(137, 122, 65), 41)
                .color(ImGuiCol.BorderShadow, new Color(0, 0, 0), 0)
                .color(ImGuiCol.FrameBg, new Color(39, 39, 39), 255)
                .color(ImGuiCol.TitleBgCollapsed, new Color(51, 56, 68), 191)
                .color(ImGuiCol.MenuBarBg, new Color(51, 56, 68), 120)
                .color(ImGuiCol.ScrollbarBg, new Color(48, 48, 48), 255)
                .color(ImGuiCol.ScrollbarGrab, new Color(23, 23, 23), 255)
                .color(ImGuiCol.Button, new Color(119, 196, 211), 36)
                .color(ImGuiCol.Separator, new Color(109, 109, 127), 127)
                .color(ImGuiCol.ResizeGrip, new Color(211, 119, 209), 10)
                .color(ImGuiCol.PlotLines, new Color(219, 237, 226), 161)
                .color(ImGuiCol.PlotHistogram, new Color(219, 237, 226), 161)
                .color(ImGuiCol.TableHeaderBg, new Color(47, 47, 47), 255)
                .color(ImGuiCol.TableBorderStrong, new Color(90, 90, 90), 255)
                .color(ImGuiCol.TableBorderLight, new Color(65, 65, 65), 255)
                .color(ImGuiCol.TableRowBg, new Color(0, 0, 0), 0)
                .color(ImGuiCol.TableRowBgAlt, new Color(255, 255, 255), 15)
                .color(ImGuiCol.DragDropTarget, new Color(255, 255, 0), 229)
                .color(ImGuiCol.NavWindowingHighlight, new Color(255, 255, 255), 178)
                .color(ImGuiCol.NavWindowingDimBg, new Color(204, 204, 204), 51)
                .color(ImGuiCol.ModalWindowDimBg, new Color(204, 204, 204), 89)
                .color(ImGuiCol.FrameBgHovered, darker2, 199)
                .color(ImGuiCol.FrameBgActive, darker1, 255)
                .color(ImGuiCol.TitleBg, darker3, 255)
                .color(ImGuiCol.TitleBgActive, darker2, 255)
                .color(ImGuiCol.ScrollbarGrabHovered, darker2, 199)
                .color(ImGuiCol.ScrollbarGrabActive, darker1, 255)
                .color(ImGuiCol.CheckMark, mainColor, 255)
                .color(ImGuiCol.SliderGrab, mainColor, 255)
                .color(ImGuiCol.SliderGrabActive, mainColor, 255)
                .color(ImGuiCol.ButtonHovered, darker1, 219)
                .color(ImGuiCol.ButtonActive, darker2, 255)
                .color(ImGuiCol.Header, darker3, 194)
                .color(ImGuiCol.HeaderHovered, darker2, 219)
                .color(ImGuiCol.HeaderActive, darker1, 255)
                .color(ImGuiCol.SeparatorHovered, darker1, 199)
                .color(ImGuiCol.SeparatorActive, mainColor, 255)
                .color(ImGuiCol.ResizeGripHovered, darker1, 199)
                .color(ImGuiCol.ResizeGripActive, darker1, 255)
                .color(ImGuiCol.Tab, darker2, 220)
                .color(ImGuiCol.TabHovered, mainColor, 255)
                .color(ImGuiCol.TabActive, mainColor, 255)
                .color(ImGuiCol.TabUnfocused, darker5, 248)
                .color(ImGuiCol.TabUnfocusedActive, darker1, 255)
                .color(ImGuiCol.PlotLinesHovered, darker3, 255)
                .color(ImGuiCol.PlotHistogramHovered, darker3, 255)
                .color(ImGuiCol.TextSelectedBg, darker1, 199)
                .color(ImGuiCol.NavHighlight, mainColor, 255);
    }

    public static ImGuiStyleSheet crimson() {
        Color base = new Color(51, 56, 69);
        Color accent = new Color(235, 46, 74);
        Color slider = new Color(120, 196, 212);
        Color check = new Color(181, 56, 69);

        return new ImGuiStyleSheet()
                .alpha(0.95f)
                .windowMinSize(160f, 20f)
                .framePadding(4f, 2f)
                .itemSpacing(6f, 2f)
                .itemInnerSpacing(2f, 4f)
                .rounding(4f, 2f, 2f)
                .indentSpacing(6f)
                .columnsMinSpacing(50f)
                .grabMinSize(14f)
                .grabRounding(16f)
                .scrollbarSize(12f)
                .scrollbarRounding(16f)
                .color(ImGuiCol.Text, new Color(219, 237, 227), 199)
                .color(ImGuiCol.TextDisabled, new Color(219, 237, 227), 71)
                .color(ImGuiCol.WindowBg, new Color(33, 36, 43), 255)
                .color(ImGuiCol.Border, new Color(79, 79, 255), 0)
                .color(ImGuiCol.BorderShadow, new Color(0, 0, 0), 0)
                .color(ImGuiCol.FrameBg, base, 255)
                .color(ImGuiCol.FrameBgHovered, accent, 199)
                .color(ImGuiCol.FrameBgActive, accent, 255)
                .color(ImGuiCol.TitleBg, base, 255)
                .color(ImGuiCol.TitleBgCollapsed, base, 191)
                .color(ImGuiCol.TitleBgActive, accent, 255)
                .color(ImGuiCol.MenuBarBg, base, 120)
                .color(ImGuiCol.ScrollbarBg, base, 255)
                .color(ImGuiCol.ScrollbarGrab, new Color(23, 38, 41), 255)
                .color(ImGuiCol.ScrollbarGrabHovered, accent, 199)
                .color(ImGuiCol.ScrollbarGrabActive, accent, 255)
                .color(ImGuiCol.CheckMark, check, 255)
                .color(ImGuiCol.SliderGrab, slider, 36)
                .color(ImGuiCol.SliderGrabActive, accent, 255)
                .color(ImGuiCol.Button, slider, 36)
                .color(ImGuiCol.Tab, new Color(24, 28, 42), 255)
                .color(ImGuiCol.TabHovered, accent, 180)
                .color(ImGuiCol.TabActive, accent, 230)
                .color(ImGuiCol.TabUnfocused, new Color(20, 23, 35), 255)
                .color(ImGuiCol.TabUnfocusedActive, accent.darker(), 220)
                .color(ImGuiCol.ButtonHovered, accent, 219)
                .color(ImGuiCol.ButtonActive, accent, 255)
                .color(ImGuiCol.Header, accent, 194)
                .color(ImGuiCol.HeaderHovered, accent, 219)
                .color(ImGuiCol.HeaderActive, accent, 255)
                .color(ImGuiCol.Separator, new Color(36, 41, 48), 255)
                .color(ImGuiCol.SeparatorHovered, accent, 199)
                .color(ImGuiCol.SeparatorActive, accent, 255)
                .color(ImGuiCol.ResizeGrip, slider, 10)
                .color(ImGuiCol.ResizeGripHovered, accent, 199)
                .color(ImGuiCol.ResizeGripActive, accent, 255)
                .color(ImGuiCol.PlotLines, new Color(219, 237, 227), 161)
                .color(ImGuiCol.PlotLinesHovered, accent, 255)
                .color(ImGuiCol.PlotHistogram, new Color(219, 237, 227), 161)
                .color(ImGuiCol.PlotHistogramHovered, accent, 255)
                .color(ImGuiCol.TextSelectedBg, accent, 110)
                .color(ImGuiCol.PopupBg, base, 230)
                .color(ImGuiCol.ModalWindowDimBg, base, 186);
    }
    public static ImGuiStyleSheet midnight() {
        Color base = new Color(18, 22, 34);
        Color accent = new Color(94, 129, 244);
        Color accentDark = accent.darker();
        Color text = new Color(210, 218, 235);

        return new ImGuiStyleSheet()
                .alpha(0.97f)
                .rounding(5f, 3f, 3f)
                .windowPadding(10f, 10f)
                .framePadding(6f, 4f)
                .itemSpacing(8f, 6f)
                .grabRounding(12f)
                .scrollbarRounding(12f)
                .scrollbarSize(10f)
                .color(ImGuiCol.Text, text, 235)
                .color(ImGuiCol.TextDisabled, text, 80)
                .color(ImGuiCol.WindowBg, base, 250)
                .color(ImGuiCol.ChildBg, base, 0)
                .color(ImGuiCol.PopupBg, base, 235)
                .color(ImGuiCol.Border, accentDark, 60)
                .color(ImGuiCol.BorderShadow, new Color(0, 0, 0), 0)
                .color(ImGuiCol.FrameBg, new Color(28, 33, 48), 255)
                .color(ImGuiCol.FrameBgHovered, accentDark, 180)
                .color(ImGuiCol.FrameBgActive, accent, 220)
                .color(ImGuiCol.TitleBg, new Color(14, 17, 27), 255)
                .color(ImGuiCol.TitleBgActive, accentDark, 255)
                .color(ImGuiCol.TitleBgCollapsed, new Color(14, 17, 27), 191)
                .color(ImGuiCol.MenuBarBg, new Color(14, 17, 27), 120)
                .color(ImGuiCol.ScrollbarBg, base, 255)
                .color(ImGuiCol.ScrollbarGrab, accentDark, 150)
                .color(ImGuiCol.ScrollbarGrabHovered, accent, 190)
                .color(ImGuiCol.ScrollbarGrabActive, accent, 255)
                .color(ImGuiCol.CheckMark, accent, 255)
                .color(ImGuiCol.SliderGrab, accent, 200)
                .color(ImGuiCol.SliderGrabActive, accent, 255)
                .color(ImGuiCol.Button, accentDark, 140)
                .color(ImGuiCol.ButtonHovered, accent, 190)
                .color(ImGuiCol.ButtonActive, accent, 255)
                .color(ImGuiCol.Header, accentDark, 160)
                .color(ImGuiCol.HeaderHovered, accent, 190)
                .color(ImGuiCol.HeaderActive, accent, 230)
                .color(ImGuiCol.Separator, new Color(40, 46, 64), 200)
                .color(ImGuiCol.SeparatorHovered, accent, 160)
                .color(ImGuiCol.SeparatorActive, accent, 255)
                .color(ImGuiCol.ResizeGrip, accent, 20)
                .color(ImGuiCol.ResizeGripHovered, accent, 150)
                .color(ImGuiCol.ResizeGripActive, accent, 255)
                .color(ImGuiCol.Tab, new Color(24, 28, 42), 255)
                .color(ImGuiCol.TabHovered, accent, 180)
                .color(ImGuiCol.TabActive, accent, 230)
                .color(ImGuiCol.TabUnfocused, new Color(20, 23, 35), 255)
                .color(ImGuiCol.TabUnfocusedActive, accentDark, 220)
                .color(ImGuiCol.PlotLines, text, 161)
                .color(ImGuiCol.PlotLinesHovered, accent, 255)
                .color(ImGuiCol.PlotHistogram, text, 161)
                .color(ImGuiCol.PlotHistogramHovered, accent, 255)
                .color(ImGuiCol.TableHeaderBg, new Color(24, 28, 42), 255)
                .color(ImGuiCol.TableBorderStrong, new Color(50, 56, 76), 255)
                .color(ImGuiCol.TableBorderLight, new Color(36, 40, 56), 255)
                .color(ImGuiCol.TableRowBg, new Color(0, 0, 0), 0)
                .color(ImGuiCol.TableRowBgAlt, new Color(255, 255, 255), 10)
                .color(ImGuiCol.TextSelectedBg, accent, 90)
                .color(ImGuiCol.DragDropTarget, accent, 229)
                .color(ImGuiCol.NavHighlight, accent, 255)
                .color(ImGuiCol.NavWindowingHighlight, new Color(255, 255, 255), 178)
                .color(ImGuiCol.NavWindowingDimBg, new Color(10, 12, 18), 100)
                .color(ImGuiCol.ModalWindowDimBg, new Color(10, 12, 18), 130);
    }

    public static ImGuiStyleSheet csgo() {
        Color scheme = new Color(162, 144, 225);
        Color text = new Color(255, 255, 255);
        Color disabled = new Color(78, 78, 78);
        Color window = new Color(10, 10, 10);
        Color child = new Color(8, 8, 8);
        Color border = new Color(255, 255, 255);
        Color frame = new Color(19, 19, 19);
        Color frameHover = new Color(23, 23, 23);
        Color frameActive = new Color(27, 27, 27);
        Color button = new Color(26, 25, 26);
        Color buttonHover = new Color(36, 35, 36);
        Color buttonActive = new Color(46, 45, 46);
        Color grab = new Color(32, 31, 32);
        Color grabHover = new Color(37, 36, 37);
        Color grabActive = new Color(42, 41, 42);

        return new ImGuiStyleSheet()
                .rounding(0f, 0f, 0f)
                .windowPadding(0f, 0f)
                .windowMinSize(480f, 330f)
                .framePadding(4f, 4f)
                .itemSpacing(8f, 4f)
                .itemInnerSpacing(8f, 3f)
                .grabMinSize(12f)
                .grabRounding(0f)
                .scrollbarSize(9f)
                .scrollbarRounding(0f)
                .color(ImGuiCol.Text, text, 255)
                .color(ImGuiCol.TextDisabled, disabled, 255)
                .color(ImGuiCol.WindowBg, window, 255)
                .color(ImGuiCol.ChildBg, child, 255)
                .color(ImGuiCol.PopupBg, new Color(20, 20, 20), 240)
                .color(ImGuiCol.Border, border, 15)
                .color(ImGuiCol.BorderShadow, new Color(0, 0, 0), 255)
                .color(ImGuiCol.FrameBg, frame, 255)
                .color(ImGuiCol.FrameBgHovered, frameHover, 255)
                .color(ImGuiCol.FrameBgActive, frameActive, 255)
                .color(ImGuiCol.TitleBg, new Color(10, 10, 10), 255)
                .color(ImGuiCol.TitleBgActive, new Color(10, 10, 10), 255)
                .color(ImGuiCol.TitleBgCollapsed, new Color(10, 10, 10), 130)
                .color(ImGuiCol.MenuBarBg, new Color(36, 36, 36), 255)
                .color(ImGuiCol.ScrollbarBg, new Color(0, 0, 0), 0)
                .color(ImGuiCol.ScrollbarGrab, grab, 255)
                .color(ImGuiCol.ScrollbarGrabHovered, grabHover, 255)
                .color(ImGuiCol.ScrollbarGrabActive, grabActive, 255)
                .color(ImGuiCol.CheckMark, scheme, 255)
                .color(ImGuiCol.SliderGrab, scheme, 255)
                .color(ImGuiCol.SliderGrabActive, new Color(132, 114, 195), 255)
                .color(ImGuiCol.Button, button, 255)
                .color(ImGuiCol.ButtonHovered, buttonHover, 255)
                .color(ImGuiCol.ButtonActive, buttonActive, 255)
                .color(ImGuiCol.Header, scheme, 80)
                .color(ImGuiCol.HeaderHovered, scheme, 140)
                .color(ImGuiCol.HeaderActive, scheme, 200)
                .color(ImGuiCol.Separator, border, 15)
                .color(ImGuiCol.SeparatorHovered, scheme, 180)
                .color(ImGuiCol.SeparatorActive, scheme, 255)
                .color(ImGuiCol.ResizeGrip, scheme, 50)
                .color(ImGuiCol.ResizeGripHovered, scheme, 170)
                .color(ImGuiCol.ResizeGripActive, scheme, 240)
                .color(ImGuiCol.Tab, frame, 255)
                .color(ImGuiCol.TabHovered, scheme, 180)
                .color(ImGuiCol.TabActive, scheme, 220)
                .color(ImGuiCol.TabUnfocused, child, 255)
                .color(ImGuiCol.TabUnfocusedActive, frame, 255)
                .color(ImGuiCol.PlotLines, text, 161)
                .color(ImGuiCol.PlotLinesHovered, scheme, 255)
                .color(ImGuiCol.PlotHistogram, scheme, 255)
                .color(ImGuiCol.PlotHistogramHovered, new Color(132, 114, 195), 255)
                .color(ImGuiCol.TableHeaderBg, frame, 255)
                .color(ImGuiCol.TableBorderStrong, new Color(80, 80, 90), 255)
                .color(ImGuiCol.TableBorderLight, new Color(59, 59, 64), 255)
                .color(ImGuiCol.TableRowBg, new Color(0, 0, 0), 0)
                .color(ImGuiCol.TableRowBgAlt, new Color(255, 255, 255), 15)
                .color(ImGuiCol.TextSelectedBg, scheme, 128)
                .color(ImGuiCol.DragDropTarget, scheme, 230)
                .color(ImGuiCol.NavHighlight, scheme, 255)
                .color(ImGuiCol.NavWindowingHighlight, new Color(255, 255, 255), 178)
                .color(ImGuiCol.NavWindowingDimBg, new Color(204, 204, 204), 51)
                .color(ImGuiCol.ModalWindowDimBg, new Color(204, 204, 204), 89);
    }

    public static ImGuiStyleSheet amethyst() {
        Color base = new Color(30, 24, 40);
        Color accent = new Color(178, 108, 240);
        Color accentDark = accent.darker();
        Color text = new Color(228, 218, 235);

        return new ImGuiStyleSheet()
                .alpha(0.96f)
                .rounding(6f, 3f, 3f)
                .windowPadding(10f, 10f)
                .framePadding(5f, 3f)
                .itemSpacing(7f, 5f)
                .grabRounding(14f)
                .scrollbarRounding(14f)
                .scrollbarSize(10f)
                .color(ImGuiCol.Text, text, 230)
                .color(ImGuiCol.TextDisabled, text, 75)
                .color(ImGuiCol.WindowBg, base, 248)
                .color(ImGuiCol.ChildBg, base, 0)
                .color(ImGuiCol.PopupBg, base, 232)
                .color(ImGuiCol.Border, accentDark, 70)
                .color(ImGuiCol.BorderShadow, new Color(0, 0, 0), 0)
                .color(ImGuiCol.FrameBg, new Color(40, 32, 52), 255)
                .color(ImGuiCol.FrameBgHovered, accentDark, 190)
                .color(ImGuiCol.FrameBgActive, accent, 230)
                .color(ImGuiCol.TitleBg, new Color(22, 17, 30), 255)
                .color(ImGuiCol.TitleBgActive, accentDark, 255)
                .color(ImGuiCol.TitleBgCollapsed, new Color(22, 17, 30), 191)
                .color(ImGuiCol.MenuBarBg, new Color(22, 17, 30), 120)
                .color(ImGuiCol.ScrollbarBg, base, 255)
                .color(ImGuiCol.ScrollbarGrab, accentDark, 160)
                .color(ImGuiCol.ScrollbarGrabHovered, accent, 200)
                .color(ImGuiCol.ScrollbarGrabActive, accent, 255)
                .color(ImGuiCol.CheckMark, accent, 255)
                .color(ImGuiCol.SliderGrab, accent, 210)
                .color(ImGuiCol.SliderGrabActive, accent, 255)
                .color(ImGuiCol.Button, accentDark, 150)
                .color(ImGuiCol.ButtonHovered, accent, 200)
                .color(ImGuiCol.ButtonActive, accent, 255)
                .color(ImGuiCol.Header, accentDark, 170)
                .color(ImGuiCol.HeaderHovered, accent, 200)
                .color(ImGuiCol.HeaderActive, accent, 240)
                .color(ImGuiCol.Separator, new Color(54, 44, 68), 200)
                .color(ImGuiCol.SeparatorHovered, accent, 170)
                .color(ImGuiCol.SeparatorActive, accent, 255)
                .color(ImGuiCol.ResizeGrip, accent, 25)
                .color(ImGuiCol.ResizeGripHovered, accent, 160)
                .color(ImGuiCol.ResizeGripActive, accent, 255)
                .color(ImGuiCol.Tab, new Color(34, 27, 45), 255)
                .color(ImGuiCol.TabHovered, accent, 190)
                .color(ImGuiCol.TabActive, accent, 240)
                .color(ImGuiCol.TabUnfocused, new Color(27, 21, 36), 255)
                .color(ImGuiCol.TabUnfocusedActive, accentDark, 225)
                .color(ImGuiCol.PlotLines, text, 161)
                .color(ImGuiCol.PlotLinesHovered, accent, 255)
                .color(ImGuiCol.PlotHistogram, text, 161)
                .color(ImGuiCol.PlotHistogramHovered, accent, 255)
                .color(ImGuiCol.TableHeaderBg, new Color(34, 27, 45), 255)
                .color(ImGuiCol.TableBorderStrong, new Color(62, 50, 80), 255)
                .color(ImGuiCol.TableBorderLight, new Color(46, 37, 60), 255)
                .color(ImGuiCol.TableRowBg, new Color(0, 0, 0), 0)
                .color(ImGuiCol.TableRowBgAlt, new Color(255, 255, 255), 10)
                .color(ImGuiCol.TextSelectedBg, accent, 95)
                .color(ImGuiCol.DragDropTarget, accent, 229)
                .color(ImGuiCol.NavHighlight, accent, 255)
                .color(ImGuiCol.NavWindowingHighlight, new Color(255, 255, 255), 178)
                .color(ImGuiCol.NavWindowingDimBg, new Color(12, 9, 16), 100)
                .color(ImGuiCol.ModalWindowDimBg, new Color(12, 9, 16), 130);
    }
}